#!/usr/bin/env python
"""Pretrain a ~362M Llama-architecture model FROM SCRATCH on FineWeb-Edu.

WHAT THIS LANE IS, AND WHAT IT IS NOT
-------------------------------------
It is a measurement of what from-scratch pretraining costs on ONE Trainium1
chip: throughput, MFU, compile behaviour, and the shape of a real loss curve
descending from random initialisation.

It is NOT a claim to have produced a competitive language model. One trn1.2xlarge
is two NeuronCores. The Neuron tutorials pretrain 8B models on four
trn1.32xlarge -- 128 cores. Chinchilla-optimal for 362M parameters is roughly
7B tokens; this lane trains on a fixed ~1B-token budget chosen to fit a bounded
spend. The resulting checkpoint is undertrained BY CONSTRUCTION and the report
must say so. What transfers is the hardware characterisation, not the weights.

WHY THIS SIZE AND THIS CORPUS
-----------------------------
The architecture is SmolLM2-360M's exact shape (32 layers, hidden 960, 15 heads,
5 KV heads, intermediate 2560, vocab 49152). Two reasons. It is a real published
configuration rather than one invented to look good on this chip, and SmolLM2
was itself trained on FineWeb-Edu -- so the model/corpus pairing is the one its
designers chose, not one assembled to flatter a benchmark.

362M is also the size that makes a single chip honest. Full-parameter Adam at
bf16 costs ~8 bytes/param here (param + grad + two moments), so ~2.9 GB of the
16 GiB per core, leaving real room for activations. An 8B model would not fit
without sharding that this box cannot express.

WHY DATA PARALLEL AND NOT TENSOR PARALLEL
-----------------------------------------
Every other training lane in this study runs TP=2 because an 8B model does not
fit on one core. At 362M it does, so DP=2 is the correct shape: two full model
replicas, gradients all-reduced once per optimizer step. TP on a model this
small would add collective traffic to buy nothing, and would measure the
interconnect instead of the compute.
"""

from __future__ import annotations

import argparse
import json
import math
import os
import sys
import time
from pathlib import Path

import numpy as np

_HERE = Path(__file__).resolve().parent
if str(_HERE) not in sys.path:
    sys.path.insert(0, str(_HERE))

import phase4_lib as P4  # noqa: E402

# SmolLM2-360M's shape, pinned here so the lane is reproducible even if the Hub
# config moves. Verified against AutoConfig on 2026-08-14.
ARCH = dict(
    vocab_size=49152, hidden_size=960, num_hidden_layers=32,
    num_attention_heads=15, num_key_value_heads=5, intermediate_size=2560,
    rms_norm_eps=1e-5, tie_word_embeddings=True,
)


def parse_args(argv=None):
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--data", default="/opt/np/data/pretrain/fineweb_edu_1B.uint16.bin")
    ap.add_argument("--out", required=True)
    ap.add_argument("--tag", default="pretrain_smollm360m")
    ap.add_argument("--device-profile", default=os.environ.get("NP_DEVICE", "trn1"))
    # seq 1024, not the 2048 the rest of the study uses. Attempt 3 (mb=1,
    # accum=2, seq=2048) cleared the instruction ceiling and then hit the other
    # one:
    #
    #   NCC_EOOM001  peak HBM 16.20GB exceeds the 16.00GB per-core limit
    #                780MB I/O + 827MB intermediate + 14.63GB scratchpad,
    #                of which 6.79GB is anticipated SBUF spills
    #
    # Over by 1.25%. The two ceilings pull in opposite directions: gradient
    # checkpointing would cut activation memory but ADD recompute instructions,
    # pushing back toward the 5M limit just escaped. Sequence length is the one
    # lever that relieves both at once -- logits shrink linearly, attention
    # quadratically, and the instruction count falls rather than rises.
    #
    # This is a DECLARED divergence from the SFT lanes' 2048 and must be read as
    # one: the pretraining lane's throughput is not directly comparable to the
    # 8B fine-tuning lanes. 1024 is a standard pretraining context for a model
    # this size, so the lane remains internally coherent.
    ap.add_argument("--seq-len", type=int, default=1024)
    # micro_batch 1, NOT the 8 a 362M model's memory would happily allow.
    #
    # The first attempt used 8 and died at compile with NCC_EVRF007:
    # "Instructions generated by compiler 37,536,776 exceeds the typical limit
    # of 5,000,000". The binding constraint on this chip is GRAPH SIZE, not HBM,
    # and the biggest tensor in a small-model pretrain is not the weights -- it
    # is the logits, micro_batch x seq_len x vocab. At mb=8 that is
    # 8*2048*49152 = 805M elements, versus 262M in the 8B LoRA lane that
    # compiles fine. mb=1 puts it at 100M, comfortably inside.
    #
    # The tempting compensation -- raise grad_accum to keep tokens/step -- is
    # WRONG on this stack: gradient accumulation is unrolled into the compiled
    # graph here (the finding behind the 146.7% MFU control), so a bigger
    # grad_accum makes the graph bigger too. Tokens per optimizer step is
    # therefore allowed to fall rather than be bought back.
    ap.add_argument("--micro-batch", type=int, default=1)
    # grad_accum 2, after mb=1/accum=4 still came in 18% over the ceiling at
    # 5,919,820 instructions (NCC_EXTP004). Because accumulation is UNROLLED
    # into the compiled graph on this stack, each micro-step is another copy of
    # forward+backward, so halving the depth roughly halves the graph.
    #
    # Measured ceiling series, all at seq 2048 on one Trainium1:
    #   mb=8 accum=4   37,536,776 instructions   NCC_EVRF007
    #   mb=1 accum=4    5,919,820 instructions   NCC_EXTP004
    #   mb=1 accum=2    (this configuration)
    #
    # The compiler suggests --optlevel=1 instead. Rejected: it would make this
    # the only lane in the study built with non-default compiler settings, and
    # an MFU measured under a different optimiser level is not comparable to
    # the Phase-1/2/3 numbers it sits beside. Shrinking the graph costs
    # tokens-per-step, which is merely a smaller optimizer step; changing the
    # compiler would cost comparability, which is the study's whole point.
    ap.add_argument("--grad-accum", type=int, default=2)
    ap.add_argument("--lr", type=float, default=3e-4)
    ap.add_argument("--min-lr-ratio", type=float, default=0.1)
    ap.add_argument("--warmup-steps", type=int, default=100)
    # A PER-STEP LR SCHEDULE RECOMPILES THE GRAPH ON EVERY STEP.
    #
    # Measured 2026-08-14: with the cosine schedule below, a 60-step probe
    # compiled three distinct graphs in two steps. Step 1 took 82 s, step 2 took
    # 3,213,869 ms -- 53 minutes -- and the second rank sat logging "Another
    # process must be compiling ... been waiting for: 23.0 minutes".
    #
    # The cause is that `param_group["lr"] = <python float>` is traced into the
    # XLA graph as a CONSTANT. A new LR value is therefore a new graph, and a
    # new graph on this stack is a full neuronx-cc compile. Nothing else differs
    # between consecutive steps: the data is a tensor and the loss is an output.
    #
    # This matters well beyond this lane. Every real pretraining run uses warmup
    # plus decay, so the naive schedule is unusable on Trainium unless the LR is
    # held in a device tensor the optimizer reads, or held piecewise-constant
    # and changed rarely enough to amortise the compile.
    #
    # 'constant' is the default because THROUGHPUT is what this lane measures,
    # and MFU does not depend on the LR value. The schedule used is recorded in
    # the result so the number is never mistaken for one from a scheduled run.
    ap.add_argument("--lr-schedule", choices=["constant", "cosine"],
                    default="constant")
    ap.add_argument("--weight-decay", type=float, default=0.1)
    ap.add_argument("--grad-clip", type=float, default=1.0)
    ap.add_argument("--seed", type=int, default=42)
    ap.add_argument("--gradient-checkpointing", type=int, default=0)
    ap.add_argument("--attn", default="eager",
                    help="eager is the safe default for a random-init model on XLA")
    # THE SPEND BOUND. Whichever binds first wins, and the result records which.
    ap.add_argument("--target-tokens", type=float, default=1e9)
    ap.add_argument("--max-hours", type=float, default=8.0)
    ap.add_argument("--max-steps", type=int, default=-1)
    ap.add_argument("--log-every", type=int, default=10)
    ap.add_argument("--nproc-per-node", type=int, default=None)
    return ap.parse_args(argv)


def torchrun_argv(script, argv, nproc):
    return [sys.executable, "-m", "torch.distributed.run",
            f"--nproc_per_node={nproc}", script, *argv]


class ChunkSampler:
    """Non-overlapping seq_len+1 windows over the token stream, seeded and sharded.

    Non-overlapping rather than random offsets so a token is seen at most once
    in the budget -- with only ~1B tokens for a 362M model the run is already
    far under Chinchilla, and resampling would quietly make the effective corpus
    even smaller.
    """

    def __init__(self, path, seq_len, rank, world, seed):
        self.tokens = np.memmap(path, dtype=np.uint16, mode="r")
        self.seq_len = seq_len
        n_chunks = (len(self.tokens) - 1) // seq_len
        order = np.random.default_rng(seed).permutation(n_chunks)
        self.order = order[rank::world]          # disjoint shard per rank
        self.n = len(self.order)
        self.i = 0

    def batch(self, micro_batch):
        idx = [self.order[(self.i + k) % self.n] for k in range(micro_batch)]
        self.i = (self.i + micro_batch) % self.n
        s = self.seq_len
        # int64 for the embedding lookup; uint16 on disk is a storage choice only.
        return np.stack([np.asarray(self.tokens[j * s: j * s + s + 1], dtype=np.int64)
                         for j in idx])


def lr_at(step, total, args):
    """Linear warmup then cosine decay to min_lr_ratio -- the standard recipe.

    Deliberately not tuned. A tuned pretraining schedule against an untuned
    baseline elsewhere in the study would not be a comparison.

    Returns a CONSTANT when args.lr_schedule == "constant". That is not a
    modelling preference; it is what makes the lane measurable at all. See the
    --lr-schedule help: a changing LR scalar is traced into the XLA graph as a
    constant, so a schedule recompiles on every single step.
    """
    if getattr(args, "lr_schedule", "cosine") == "constant":
        return args.lr
    if step < args.warmup_steps:
        return args.lr * (step + 1) / max(1, args.warmup_steps)
    prog = (step - args.warmup_steps) / max(1, total - args.warmup_steps)
    prog = min(1.0, max(0.0, prog))
    lo = args.lr * args.min_lr_ratio
    return lo + 0.5 * (args.lr - lo) * (1.0 + math.cos(math.pi * prog))


def main(argv=None):
    argv = list(sys.argv[1:] if argv is None else argv)
    args = parse_args(argv)
    profile = P4.profile_for(args.device_profile)
    nproc = args.nproc_per_node or profile["nproc"]

    # Re-exec under torchrun exactly as sft_lora does, so the lane is launched
    # the same way as every other training lane in the study.
    if "LOCAL_RANK" not in os.environ:
        os.execv(sys.executable, torchrun_argv(__file__, argv, nproc))

    import torch
    import torch_xla.core.xla_model as xm
    import torch_xla.distributed.xla_backend  # noqa: F401  registers the 'xla' backend
    from transformers import AutoTokenizer, LlamaConfig, LlamaForCausalLM

    # torch_xla 2.9 moved these onto torch_xla.runtime and dropped
    # xm.xrt_world_size entirely -- the stack audit caught it returning n/a.
    # Resolve through runtime first and fall back, so the lane is not pinned to
    # one torch_xla point release.
    import torch_xla.runtime as xr

    torch.manual_seed(args.seed)
    if not torch.distributed.is_initialized():
        torch.distributed.init_process_group("xla")
    rank = xr.global_ordinal() if hasattr(xr, "global_ordinal") else xm.get_ordinal()
    world = xr.world_size() if hasattr(xr, "world_size") else torch.distributed.get_world_size()
    master = rank == 0
    import torch_xla
    device = torch_xla.device() if hasattr(torch_xla, "device") else xm.xla_device()

    def say(*a):
        if master:
            print(*a, flush=True)

    if not Path(args.data).exists():
        raise SystemExit(f"token file missing: {args.data} -- run prep first")

    say(f"[pretrain] rank {rank}/{world} device={device}")
    cfg = LlamaConfig(max_position_embeddings=args.seq_len,
                      attn_implementation=args.attn, **ARCH)
    model = LlamaForCausalLM(cfg)            # RANDOM INIT -- this is the point
    model = model.to(torch.bfloat16).to(device)
    if args.gradient_checkpointing:
        model.gradient_checkpointing_enable()
    model.train()

    n_params = sum(p.numel() for p in model.parameters())
    say(f"[pretrain] {n_params/1e6:.1f}M parameters, all trainable")

    # capturable=True is load-bearing, not a tuning knob.
    #
    # A plain torch.optim.AdamW recompiles the graph on EVERY optimizer step on
    # this stack. The cause is bias correction: AdamW computes
    #
    #     bias_correction1 = 1 - beta1 ** _get_value(step_t)
    #
    # and _get_value() calls .item() on a non-capturable step, producing a
    # PYTHON FLOAT that is traced into the XLA graph as a constant. The constant
    # changes every step, so every step is a new graph and a new neuronx-cc
    # compile.
    #
    # Measured: a 40-step probe completed 2 steps and compiled 3 graphs. That
    # first looked like the learning-rate schedule -- also a per-step Python
    # scalar -- but pinning the LR to a constant did NOT fix it, which ruled the
    # LR out as the sole cause and pointed here.
    #
    # capturable=True keeps step as a device tensor and does the bias correction
    # with tensor ops, so the graph is stable across steps. torch 2.9 lists
    # 'xla' in _get_capturable_supported_devices(), so this is a supported
    # configuration rather than a trick.
    #
    # This is also what optimum-neuron does indirectly for the SFT lanes: it
    # hands plain AdamW to its own accelerator with zero_1=True, which wraps it
    # in an XLA-aware Zero-1 optimizer. This lane owns its loop, so it has to
    # ask for the equivalent explicitly.
    opt = torch.optim.AdamW(model.parameters(), lr=args.lr, betas=(0.9, 0.95),
                            weight_decay=args.weight_decay, eps=1e-8,
                            capturable=True, foreach=False)

    tokens_per_step = args.seq_len * args.micro_batch * args.grad_accum * world
    total_steps = int(args.target_tokens // tokens_per_step)
    if args.max_steps > 0:
        total_steps = min(total_steps, args.max_steps)
    say(f"[pretrain] {tokens_per_step} tok/step, {total_steps} steps planned, "
        f"cap {args.max_hours}h")

    sampler = ChunkSampler(args.data, args.seq_len, rank, world, args.seed)
    log = P4.StepLog(warmup=10)
    deadline = time.time() + args.max_hours * 3600.0
    stopped = "target_tokens"
    step = 0

    while step < total_steps:
        if time.time() > deadline:
            stopped = "max_hours"
            break
        for g in opt.param_groups:
            g["lr"] = lr_at(step, total_steps, args)

        opt.zero_grad(set_to_none=True)
        last = None
        for _ in range(args.grad_accum):
            b = sampler.batch(args.micro_batch)
            ids = torch.from_numpy(b[:, :-1]).to(device)
            lab = torch.from_numpy(b[:, 1:]).to(device)
            loss = model(input_ids=ids, labels=lab).loss / args.grad_accum
            loss.backward()
            last = loss
        if args.grad_clip:
            torch.nn.utils.clip_grad_norm_(model.parameters(), args.grad_clip)
        xm.optimizer_step(opt)               # all-reduces grads across the DP group

        # .item() forces an XLA sync. Every other lane in this study pays it to
        # get a real loss trace, and a pretraining curve is the lane's headline
        # output -- a run with no loss curve would prove nothing descended.
        lv = last.detach().float().item() * args.grad_accum
        ms = log.tick(lv)
        step += 1
        if master and (step % args.log_every == 0 or step <= 3):
            say(f"  step {step}/{total_steps} loss {lv:.4f} {ms:.0f}ms "
                f"lr {opt.param_groups[0]['lr']:.2e}")
    else:
        stopped = "target_tokens"

    if master:
        tok_seen = tokens_per_step * step
        tokenizer_name = "HuggingFaceTB/SmolLM2-360M"
        try:
            AutoTokenizer.from_pretrained(tokenizer_name)
        except Exception:
            pass
        res = P4.emit_result(
            args.out, tag=args.tag, stage="pretrain",
            model=f"llama-arch-{n_params/1e6:.0f}M-from-scratch",
            dataset="HuggingFaceFW/fineweb-edu:sample-10BT",
            params={
                "params_total": n_params,
                "params_trainable": n_params,
                "params_frozen": 0,
                "params_note": ("Full-parameter pretraining from random "
                                "initialisation; nothing is frozen, so FLOPs/token "
                                "is the dense 6N."),
            },
            config={
                "architecture": "SmolLM2-360M shape (published config, not tuned here)",
                **ARCH,
                "seq_len": args.seq_len,
                "micro_batch": args.micro_batch,
                "grad_accum": args.grad_accum,
                "gradient_checkpointing": bool(args.gradient_checkpointing),
                "attn_implementation": args.attn,
                "dtype": "bfloat16",
                "optimizer": "AdamW(0.9,0.95) wd=0.1 eps=1e-8",
                "lr": args.lr, "min_lr_ratio": args.min_lr_ratio,
                "lr_schedule": args.lr_schedule,
                "schedule": ("constant (a per-step schedule recompiles the XLA "
                             "graph every step on this stack -- measured: 3 "
                             "graphs in 2 steps, a 53-minute step 2. The LR "
                             "value does not affect throughput or MFU, which "
                             "is what this lane measures.)"
                             if args.lr_schedule == "constant"
                             else "linear warmup -> cosine decay"),
                "warmup_steps": (args.warmup_steps
                                 if args.lr_schedule != "constant" else 0),
                "grad_clip": args.grad_clip,
                "seed": args.seed,
                "world_size": world,
                "data_parallel_size": world,
                "tensor_parallel_size": 1,
                "pipeline_parallel_size": 1,
                "parallelism_note": ("DP=2, not TP=2 as elsewhere in this study: a "
                                     "362M model fits on one core, so tensor "
                                     "parallelism would measure the interconnect "
                                     "rather than the compute."),
                "tokenizer": tokenizer_name,
            },
            log=log, tokens_per_step=tokens_per_step, profile=profile,
            gradient_checkpointing=bool(args.gradient_checkpointing),
            extra={
                "tokens_trained": tok_seen,
                "steps_completed": step,
                "steps_planned": total_steps,
                "stopped_because": stopped,
                "attention_flops_per_token": P4.attention_flops_per_token(
                    ARCH["num_hidden_layers"], ARCH["hidden_size"], args.seq_len,
                    bool(args.gradient_checkpointing)),
                "undertrained_by_construction": {
                    "tokens_trained": tok_seen,
                    "chinchilla_optimal_tokens": int(20 * n_params),
                    "ratio": round(tok_seen / (20 * n_params), 4),
                    "why": ("Chinchilla-optimal is ~20 tokens per parameter. This "
                            "lane trains on a fixed budget chosen to bound spend on "
                            "one chip, so the checkpoint is undertrained on purpose. "
                            "The hardware measurement is the deliverable; the "
                            "weights are not a model release."),
                },
            })
        say(f"[pretrain] {stopped}: {step} steps, {tok_seen/1e6:.1f}M tokens, "
            f"{res.get('tokens_per_s')} tok/s, MFU {res.get('mfu_pct')}%")
    xm.rendezvous("pretrain_done")
    return 0


if __name__ == "__main__":
    sys.exit(main())
